name: face_it_desktop 
description: "Face it destktop app"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cl_basic_types:
    path: ../../cl_basic_types
  flutter:
    sdk: flutter
  flutter_riverpod: 2.5.1  
  shadcn_ui: ^0.28.0
  socket_io_client: ^3.1.2

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  intl: ^0.20.2
  image_picker: ^1.2.0
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.8
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
