name: face_it_desktop 
description: "Face it destktop app"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  background_downloader: ^9.2.5
  cl_basic_types:
    path: ../../cl_basic_types
  cl_servers:
    path: ../../cl_servers
  colan_widgets:
    path: ../../colan_widgets
  collection: ^1.19.1
  content_store:
    path : ../../content_store
  dotted_border: ^3.1.0
  fl_chart: 1.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: 2.5.1  
  google_fonts: ^6.3.0
  image_picker: ^1.2.0
  intl: ^0.20.2

  material_design_icons_flutter: ^7.0.7296
  path: ^1.9.1
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.8
  shadcn_ui: ^0.38.0
  shimmer: ^3.0.0
  socket_io_client: ^3.1.2
  store:
    path: ../../store
  vertical_percent_indicator: ^0.0.1
  window_size: ^0.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/cloud_on_lan_128px_color.png