name: keep_it
description: An app allows you to preserve the images you get from web in an organized manner, without messing it up with photos.
publish_to: "none"
homepage: htts://www.cloudonlanapps.com

version: 0.1.0+1

environment:
  sdk: ^3.9.2

dependencies:
  camera: ^0.11.0+1
  cl_basic_types:
    path: ../cl_basic_types
  cl_camera:
    path: ../cl_camera
  cl_entity_viewers:
    path: ../cl_entity_viewers
  cl_extensions:
    path: ../cl_extensions
  cl_media_tools:
    path: ../cl_media_tools
  cl_server_dart_client:
    path: ../../../sdks/dartsdk
  colan_services:
    path: ../colan_services
  colan_widgets:
    path: ../colan_widgets
  
  flutter:
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  form_factory:
    path: ../form_factory
  image_picker: ^1.1.2
  local_store:
    path: ../local_store
  media_editors:
    path: ../media_editors
  path: ^1.9.1
  shadcn_ui: ^0.38.0
  share_handler: ^0.0.21
  share_plus: ^12.0.0
  shimmer: ^3.0.0
  store:
    path: ../store
  window_size: ^0.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0
  very_good_analysis: ^10.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/audios/audio1.mp3
    - assets/audios/audio2.mp3
    - assets/audios/audio3.mp3
    - assets/audios/audio4.mp3
    - assets/icon/cloud_on_lan_128px_color.png
    - assets/icon/icon.png
    - assets/icon/on_device.png
    - assets/icon/not_on_server.png
    - assets/icon/svg/minimize-svgrepo-com.svg
    - assets/icon/svg/maximize-svgrepo-com.svg
    - assets/icon/svg/audio-svgrepo-com.svg
    - assets/icon/svg/audio-off-svgrepo-com.svg
    - assets/icon/svg/rotate-left-svgrepo-com.svg
    - assets/icon/svg/rotate-right-svgrepo-com.svg
