name: cl_camera
description: "A new Flutter package project."
version: 0.0.1

publish_to: none

environment:
  sdk: ^3.9.2

dependencies:
  camera: ^0.11.0+1
  camera_macos_plus: ^0.0.4
  flutter:
    sdk: flutter
  path_provider: ^2.1.0
  permission_handler: ^12.0.0+1
  shadcn_ui: ^0.38.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
