name: colan_services
description: "Various Services"
version: 0.0.1

publish_to: none

environment:
  sdk: ^3.9.2

dependencies:
  # audio_waveforms: 1.0.5 # Upgrade has issues!
  # background_downloader: ^8.9.4
  camera: ^0.11.0+1
  cl_basic_types:
    path: ../cl_basic_types
  cl_camera:
    path: ../cl_camera
  cl_entity_viewers:
    path: ../cl_entity_viewers
  cl_extensions:
    path: ../cl_extensions
  cl_media_tools:
    path: ../cl_media_tools
  cl_server_dart_client:
    path: ../../../sdks/dartsdk
  colan_widgets:
    path: ../colan_widgets
  collection: ^1.19.0
  connectivity_plus: ^7.0.0 
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  http: ^1.5.0
  local_store:
    path: ../local_store
  nsd: ^4.0.3
  path: ^1.9.0
  path_provider: ^2.1.4
  photo_manager: ^3.2.3
  share_handler: ^0.0.21
  share_plus: ^12.0.0 
  shared_preferences: ^2.2.3
  store:
    path: ../store
  watcher: ^1.1.0


dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
