name: cl_servers
description: "A new Flutter package project."
version: 0.0.1
homepage: https://www.cloudonlanapps.com
publish_to: none
environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  cl_basic_types:
    path: ../cl_basic_types
  colan_widgets:
    path: ../colan_widgets
  collection: ^1.19.1
  connectivity_plus: ^6.1.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  http: ^1.5.0
  nsd: ^4.0.3
  path: ^1.9.1
  shadcn_ui: ^0.27.4
  socket_io_client: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  very_good_analysis: ^8.0.0

