name: cl_servers
description: "A new Flutter package project."
version: 0.0.1
homepage: https://www.cloudonlanapps.com
publish_to: none
environment:
  sdk: ^3.9.2

dependencies:
  cl_basic_types:
    path: ../cl_basic_types
  cl_server_dart_client:
    path: ../../../sdks/dartsdk
  colan_widgets:
    path: ../colan_widgets
  collection: ^1.19.1
  connectivity_plus: ^7.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  http: ^1.5.0
  meta: ^1.17.0
  nsd: ^4.0.3
  path: ^1.9.1
  shadcn_ui: ^0.38.0
  shared_preferences: ^2.3.5
  socket_io_client: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lints: ^6.0.0
  test: ^1.24.0
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
