name: colan_widgets
description: "Widgets for Colan Projects"
version: 0.0.1
publish_to: none
environment:
  sdk: ^3.9.2

dependencies:
  # audio_waveforms: ^1.0.5
  flutter:
    sdk: flutter
  material_design_icons_flutter: ^7.0.7296
  material_symbols_icons: ^4.2785.1
  percent_indicator: ^4.2.3
  progress_indicators: ^1.0.0
  shadcn_ui: ^0.38.0
  shimmer: ^3.0.0

  #scroll_to_index: ^3.0.1
  # scrollable_positioned_list: ^0.3.8
  # watcher: ^1.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
