name: online_store
description: Online Store implementation.
version: 0.0.1
# repository: https://github.com/my_org/my_repo
publish_to: none
environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  cl_basic_types:
    path: ../cl_basic_types
  cl_servers:
    path: ../cl_servers
  collection: ^1.19.0
  http: ^1.2.2
  image: ^4.5.4
  intl: ^0.20.2
  meta: ^1.12.0
  path: ^1.9.1
  store:
    path: ../store
  

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.1
  very_good_analysis: ^10.0.0
 