name: media_editors_example
description: "Example application for media_editors package."
publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  file_picker: ^8.1.7
  flutter:
    sdk: flutter
  media_editors:
    path: ../
  path: ^1.9.0
  path_provider: ^2.1.5
  shadcn_ui: ^0.38.5
  share_plus: ^10.1.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
