name: cl_basic_types
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.9.2
publish_to: none

dependencies:
  cl_extensions:
    path: ../cl_extensions
  collection: ^1.19.1
  meta: ^1.16.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
  very_good_analysis: ^10.0.0
