name: form_factory
description: "A new Flutter package project."
version: 0.0.1

publish_to: none

environment:
  sdk: ^3.9.2

dependencies:
  cl_extensions:
    path: ../cl_extensions
  flutter:
    sdk: flutter
  colan_widgets:
    path: ../colan_widgets
  shadcn_ui: ^0.38.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
