name: cl_media_viewer
description: Standalone interactive image viewer with face bounding box overlay support.
version: 1.0.0

environment:
  sdk: ^3.9.2
  flutter: '>=3.22.0'
publish_to: none

dependencies:
  flutter:
    sdk: flutter
  cl_basic_types:
    path: ../cl_basic_types
  extended_image: ^9.0.8
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  very_good_analysis: ^10.0.0
